services:
  - type: web
    name: machata-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn machata_bot.py
    envVars:
      - key: API_TOKEN
        sync: false
